name: nevis
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  get_it: ^7.0.0
  moor_flutter: ^4.0.0
  moor: ^4.2.1
  path_provider: ^2.0.1
  shared_preferences: ^2.0.5
  flutter_datetime_picker: ^1.2.8
  flutter_slidable: ^0.5.7
  intro_slider: ^2.3.3
  flutter_share: ^1.0.5
  http: ^0.12.2
  intl: ^0.16.1
  jiffy: ^3.0.1
  equatable: ^1.2.5
  flutter_bloc: ^6.1.1
  bloc: ^6.1.0
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
#  device_preview: ^0.1.9-beta

dev_dependencies:
  build_runner:
  build_verify: ^1.1.0
  moor_generator: ^4.2.2
  sqflite_common_ffi:
  flutter_test:
    sdk: flutter



# The following section is specific to Flutter.
flutter:
  assets:
    - images/launch.png
    - images/nevis.JPG
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  fonts:
    - family: RobotoMono
      fonts:
        - asset: fonts/RobotoMono-Regular.ttf
        - asset: fonts/RobotoMono-Bold.ttf
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Bold.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
