// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'note_db_models.dart';

// **************************************************************************
// SqfEntityGenerator
// **************************************************************************

//  These classes was generated by SqfEntity
//  Copyright (c) 2019, All rights reserved. Use of this source code is governed by a
//  Apache license that can be found in the LICENSE file.

//  To use these SqfEntity classes do following:
//  - import model.dart into where to use
//  - start typing ex:Note.select()... (add a few filters with fluent methods)...(add orderBy/orderBydesc if you want)...
//  - and then just put end of filters / or end of only select()  toSingle() / or toList()
//  - you can select one or return List<yourObject> by your filters and orders
//  - also you can batch update or batch delete by using delete/update methods instead of tosingle/tolist methods
//    Enjoy.. Huseyin Tokpunar

// ignore_for_file:
// BEGIN TABLES
// Note TABLE
class TableNote extends SqfEntityTableBase {
  TableNote() {
    // declare properties of EntityTable
    tableName = 'notes';
    primaryKeyName = 'id';
    primaryKeyType = PrimaryKeyType.integer_auto_incremental;
    useSoftDeleting = false;
    // when useSoftDeleting is true, creates a field named 'isDeleted' on the table, and set to '1' this field when item deleted (does not hard delete)

    // declare fields
    fields = [
      SqfEntityFieldBase('title', DbType.text, isNotNull: false),
      SqfEntityFieldBase('context', DbType.text, isNotNull: false),
      SqfEntityFieldBase('is_synced', DbType.bool,
          defaultValue: false, isNotNull: false),
      SqfEntityFieldBase('created_date', DbType.datetime,
          defaultValue: DateTime.now(),
          isNotNull: false,
          minValue: DateTime.parse('1900-01-01')),
    ];
    super.init();
  }
  static SqfEntityTableBase _instance;
  static SqfEntityTableBase get getInstance {
    return _instance = _instance ?? TableNote();
  }
}
// END TABLES

// BEGIN SEQUENCES
// identity SEQUENCE
class SequenceIdentitySequence extends SqfEntitySequenceBase {
  SequenceIdentitySequence() {
    sequenceName = 'identity';
    maxValue =
        9007199254740991; /* optional. default is max int (9.223.372.036.854.775.807) */
    cycle = false; /* optional. default is false; */
    minValue = 0; /* optional. default is 0 */
    incrementBy = 1; /* optional. default is 1 */
    startWith = 0; /* optional. default is 0 */
    super.init();
  }
  static SequenceIdentitySequence _instance;
  static SequenceIdentitySequence get getInstance {
    return _instance = _instance ?? SequenceIdentitySequence();
  }
}
// END SEQUENCES

// BEGIN DATABASE MODEL
class MyDbModel extends SqfEntityModelProvider {
  MyDbModel() {
    databaseName = myDbModel.databaseName;
    password = myDbModel.password;
    dbVersion = myDbModel.dbVersion;
    databaseTables = [
      TableNote.getInstance,
    ];

    sequences = [
      SequenceIdentitySequence.getInstance,
    ];

    bundledDatabasePath = myDbModel
        .bundledDatabasePath; //'assets/sample.db'; // This value is optional. When bundledDatabasePath is empty then EntityBase creats a new database when initializing the database
  }
  Map<String, dynamic> getControllers() {
    final controllers = <String, dynamic>{};

    return controllers;
  }
}
// END DATABASE MODEL

// BEGIN ENTITIES
// region Note
class Note {
  Note({this.id, this.title, this.context, this.is_synced, this.created_date}) {
    _setDefaultValues();
  }
  Note.withFields(this.title, this.context, this.is_synced, this.created_date) {
    _setDefaultValues();
  }
  Note.withId(
      this.id, this.title, this.context, this.is_synced, this.created_date) {
    _setDefaultValues();
  }
  Note.fromMap(Map<String, dynamic> o, {bool setDefaultValues = true}) {
    if (setDefaultValues) {
      _setDefaultValues();
    }
    id = int.tryParse(o['id'].toString());
    if (o['title'] != null) {
      title = o['title'] as String;
    }
    if (o['context'] != null) {
      context = o['context'] as String;
    }
    if (o['is_synced'] != null) {
      is_synced = o['is_synced'] == 1 || o['is_synced'] == true;
    }
    if (o['created_date'] != null) {
      created_date = int.tryParse(o['created_date'].toString()) != null
          ? DateTime.fromMillisecondsSinceEpoch(
              int.tryParse(o['created_date'].toString()))
          : DateTime.tryParse(o['created_date'].toString());
    }
  }
  // FIELDS (Note)
  int id;
  String title;
  String context;
  bool is_synced;
  DateTime created_date;

  BoolResult saveResult;
  // end FIELDS (Note)

  static const bool _softDeleteActivated = false;
  NoteManager __mnNote;

  NoteManager get _mnNote {
    return __mnNote = __mnNote ?? NoteManager();
  }

  // METHODS
  Map<String, dynamic> toMap(
      {bool forQuery = false, bool forJson = false, bool forView = false}) {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (title != null) {
      map['title'] = title;
    }

    if (context != null) {
      map['context'] = context;
    }

    if (is_synced != null) {
      map['is_synced'] = forQuery ? (is_synced ? 1 : 0) : is_synced;
    }

    if (created_date != null) {
      map['created_date'] = forJson
          ? created_date.toString()
          : forQuery
              ? created_date.millisecondsSinceEpoch
              : created_date;
    }

    return map;
  }

  Future<Map<String, dynamic>> toMapWithChildren(
      [bool forQuery = false,
      bool forJson = false,
      bool forView = false]) async {
    final map = <String, dynamic>{};
    if (id != null) {
      map['id'] = id;
    }
    if (title != null) {
      map['title'] = title;
    }

    if (context != null) {
      map['context'] = context;
    }

    if (is_synced != null) {
      map['is_synced'] = forQuery ? (is_synced ? 1 : 0) : is_synced;
    }

    if (created_date != null) {
      map['created_date'] = forJson
          ? created_date.toString()
          : forQuery
              ? created_date.millisecondsSinceEpoch
              : created_date;
    }

    return map;
  }

  /// This method returns Json String [Note]
  String toJson() {
    return json.encode(toMap(forJson: true));
  }

  /// This method returns Json String [Note]
  Future<String> toJsonWithChilds() async {
    return json.encode(await toMapWithChildren(false, true));
  }

  List<dynamic> toArgs() {
    return [
      title,
      context,
      is_synced,
      created_date != null ? created_date.millisecondsSinceEpoch : null
    ];
  }

  List<dynamic> toArgsWithIds() {
    return [
      id,
      title,
      context,
      is_synced,
      created_date != null ? created_date.millisecondsSinceEpoch : null
    ];
  }

  static Future<List<Note>> fromWebUrl(String url,
      {Map<String, String> headers}) async {
    try {
      final response = await http.get(url, headers: headers);
      return await fromJson(response.body);
    } catch (e) {
      print('SQFENTITY ERROR Note.fromWebUrl: ErrorMessage: ${e.toString()}');
      return null;
    }
  }

  Future<http.Response> postUrl(String url, {Map<String, String> headers}) {
    return http.post(url, headers: headers, body: toJson());
  }

  static Future<List<Note>> fromJson(String jsonBody) async {
    final Iterable list = await json.decode(jsonBody) as Iterable;
    var objList = <Note>[];
    try {
      objList = list
          .map((note) => Note.fromMap(note as Map<String, dynamic>))
          .toList();
    } catch (e) {
      print('SQFENTITY ERROR Note.fromJson: ErrorMessage: ${e.toString()}');
    }
    return objList;
  }

  static Future<List<Note>> fromMapList(List<dynamic> data,
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields,
      bool setDefaultValues = true}) async {
    final List<Note> objList = <Note>[];
    loadedFields = loadedFields ?? [];
    for (final map in data) {
      final obj = Note.fromMap(map as Map<String, dynamic>,
          setDefaultValues: setDefaultValues);

      objList.add(obj);
    }
    return objList;
  }

  /// returns Note by ID if exist, otherwise returns null
  ///
  /// Primary Keys: int id
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: getById(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: getById(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>returns Note if exist, otherwise returns null
  Future<Note> getById(int id,
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    if (id == null) {
      return null;
    }
    Note obj;
    final data = await _mnNote.getById([id]);
    if (data.length != 0) {
      obj = Note.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// Saves the (Note) object. If the id field is null, saves as a new record and returns new id, if id is not null then updates record

  /// <returns>Returns id
  Future<int> save() async {
    if (id == null || id == 0) {
      id = await _mnNote.insert(this);
    } else {
      // id= await _upsert(); // removed in sqfentity_gen 1.3.0+6
      await _mnNote.update(this);
    }

    return id;
  }

  /// saveAs Note. Returns a new Primary Key value of Note

  /// <returns>Returns a new Primary Key value of Note
  Future<int> saveAs() async {
    id = null;

    return save();
  }

  /// saveAll method saves the sent List<Note> as a bulk in one transaction
  ///
  /// Returns a <List<BoolResult>>
  static Future<List<dynamic>> saveAll(List<Note> notes) async {
    // final results = _mnNote.saveAll('INSERT OR REPLACE INTO notes (id,title, context, is_synced, created_date)  VALUES (?,?,?,?,?)',notes);
    // return results; removed in sqfentity_gen 1.3.0+6
    await MyDbModel().batchStart();
    for (final obj in notes) {
      await obj.save();
    }
    //    return MyDbModel().batchCommit();
    final result = await MyDbModel().batchCommit();
    for (int i = 0; i < notes.length; i++) {
      if (notes[i].id == null) {
        notes[i].id = result[i] as int;
      }
    }

    return result;
  }

  /// Updates if the record exists, otherwise adds a new row

  /// <returns>Returns id
  Future<int> upsert() async {
    try {
      if (await _mnNote.rawInsert(
              'INSERT OR REPLACE INTO notes (id,title, context, is_synced, created_date)  VALUES (?,?,?,?,?)',
              [
                id,
                title,
                context,
                is_synced,
                created_date != null
                    ? created_date.millisecondsSinceEpoch
                    : null
              ]) ==
          1) {
        saveResult = BoolResult(
            success: true, successMessage: 'Note id=$id updated successfully');
      } else {
        saveResult = BoolResult(
            success: false, errorMessage: 'Note id=$id did not update');
      }
      return id;
    } catch (e) {
      saveResult = BoolResult(
          success: false,
          errorMessage: 'Note Save failed. Error: ${e.toString()}');
      return 0;
    }
  }

  /// inserts or replaces the sent List<<Note>> as a bulk in one transaction.
  ///
  /// upsertAll() method is faster then saveAll() method. upsertAll() should be used when you are sure that the primary key is greater than zero
  ///
  /// Returns a BoolCommitResult
  Future<BoolCommitResult> upsertAll(List<Note> notes) async {
    final results = await _mnNote.rawInsertAll(
        'INSERT OR REPLACE INTO notes (id,title, context, is_synced, created_date)  VALUES (?,?,?,?,?)',
        notes);
    return results;
  }

  /// Deletes Note

  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    print('SQFENTITIY: delete Note invoked (id=$id)');
    if (!_softDeleteActivated || hardDelete) {
      return _mnNote
          .delete(QueryParams(whereString: 'id=?', whereArguments: [id]));
    } else {
      return _mnNote.updateBatch(
          QueryParams(whereString: 'id=?', whereArguments: [id]),
          {'isDeleted': 1});
    }
  }

  NoteFilterBuilder select({List<String> columnsToSelect, bool getIsDeleted}) {
    return NoteFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect;
  }

  NoteFilterBuilder distinct(
      {List<String> columnsToSelect, bool getIsDeleted}) {
    return NoteFilterBuilder(this)
      .._getIsDeleted = getIsDeleted == true
      ..qparams.selectColumns = columnsToSelect
      ..qparams.distinct = true;
  }

  void _setDefaultValues() {
    is_synced = is_synced ?? false;
    created_date = created_date ?? DateTime.now();
  }
  // END METHODS
  // CUSTOM CODES
  /*
      you must define customCode property of your SqfEntityTable constant for ex:
      const tablePerson = SqfEntityTable(
      tableName: 'person',
      primaryKeyName: 'id',
      primaryKeyType: PrimaryKeyType.integer_auto_incremental,
      fields: [
        SqfEntityField('firstName', DbType.text),
        SqfEntityField('lastName', DbType.text),
      ],
      customCode: '''
       String fullName()
       { 
         return '$firstName $lastName';
       }
      ''');
     */
  // END CUSTOM CODES
}
// endregion note

// region NoteField
class NoteField extends SearchCriteria {
  NoteField(this.noteFB) {
    param = DbParameter();
  }
  DbParameter param;
  String _waitingNot = '';
  NoteFilterBuilder noteFB;

  NoteField get not {
    _waitingNot = ' NOT ';
    return this;
  }

  NoteFilterBuilder equals(dynamic pValue) {
    param.expression = '=';
    noteFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, noteFB.parameters, param, SqlSyntax.EQuals,
            noteFB._addedBlocks)
        : setCriteria(pValue, noteFB.parameters, param, SqlSyntax.NotEQuals,
            noteFB._addedBlocks);
    _waitingNot = '';
    noteFB._addedBlocks.needEndBlock[noteFB._blockIndex] =
        noteFB._addedBlocks.retVal;
    return noteFB;
  }

  NoteFilterBuilder equalsOrNull(dynamic pValue) {
    param.expression = '=';
    noteFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, noteFB.parameters, param, SqlSyntax.EQualsOrNull,
            noteFB._addedBlocks)
        : setCriteria(pValue, noteFB.parameters, param,
            SqlSyntax.NotEQualsOrNull, noteFB._addedBlocks);
    _waitingNot = '';
    noteFB._addedBlocks.needEndBlock[noteFB._blockIndex] =
        noteFB._addedBlocks.retVal;
    return noteFB;
  }

  NoteFilterBuilder isNull() {
    noteFB._addedBlocks = setCriteria(
        0,
        noteFB.parameters,
        param,
        SqlSyntax.IsNULL.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        noteFB._addedBlocks);
    _waitingNot = '';
    noteFB._addedBlocks.needEndBlock[noteFB._blockIndex] =
        noteFB._addedBlocks.retVal;
    return noteFB;
  }

  NoteFilterBuilder contains(dynamic pValue) {
    if (pValue != null) {
      noteFB._addedBlocks = setCriteria(
          '%${pValue.toString()}%',
          noteFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          noteFB._addedBlocks);
      _waitingNot = '';
      noteFB._addedBlocks.needEndBlock[noteFB._blockIndex] =
          noteFB._addedBlocks.retVal;
    }
    return noteFB;
  }

  NoteFilterBuilder startsWith(dynamic pValue) {
    if (pValue != null) {
      noteFB._addedBlocks = setCriteria(
          '${pValue.toString()}%',
          noteFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          noteFB._addedBlocks);
      _waitingNot = '';
      noteFB._addedBlocks.needEndBlock[noteFB._blockIndex] =
          noteFB._addedBlocks.retVal;
      noteFB._addedBlocks.needEndBlock[noteFB._blockIndex] =
          noteFB._addedBlocks.retVal;
    }
    return noteFB;
  }

  NoteFilterBuilder endsWith(dynamic pValue) {
    if (pValue != null) {
      noteFB._addedBlocks = setCriteria(
          '%${pValue.toString()}',
          noteFB.parameters,
          param,
          SqlSyntax.Contains.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          noteFB._addedBlocks);
      _waitingNot = '';
      noteFB._addedBlocks.needEndBlock[noteFB._blockIndex] =
          noteFB._addedBlocks.retVal;
    }
    return noteFB;
  }

  NoteFilterBuilder between(dynamic pFirst, dynamic pLast) {
    if (pFirst != null && pLast != null) {
      noteFB._addedBlocks = setCriteria(
          pFirst,
          noteFB.parameters,
          param,
          SqlSyntax.Between.replaceAll(SqlSyntax.notKeyword, _waitingNot),
          noteFB._addedBlocks,
          pLast);
    } else if (pFirst != null) {
      if (_waitingNot != '') {
        noteFB._addedBlocks = setCriteria(pFirst, noteFB.parameters, param,
            SqlSyntax.LessThan, noteFB._addedBlocks);
      } else {
        noteFB._addedBlocks = setCriteria(pFirst, noteFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, noteFB._addedBlocks);
      }
    } else if (pLast != null) {
      if (_waitingNot != '') {
        noteFB._addedBlocks = setCriteria(pLast, noteFB.parameters, param,
            SqlSyntax.GreaterThan, noteFB._addedBlocks);
      } else {
        noteFB._addedBlocks = setCriteria(pLast, noteFB.parameters, param,
            SqlSyntax.LessThanOrEquals, noteFB._addedBlocks);
      }
    }
    _waitingNot = '';
    noteFB._addedBlocks.needEndBlock[noteFB._blockIndex] =
        noteFB._addedBlocks.retVal;
    return noteFB;
  }

  NoteFilterBuilder greaterThan(dynamic pValue) {
    param.expression = '>';
    noteFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, noteFB.parameters, param, SqlSyntax.GreaterThan,
            noteFB._addedBlocks)
        : setCriteria(pValue, noteFB.parameters, param,
            SqlSyntax.LessThanOrEquals, noteFB._addedBlocks);
    _waitingNot = '';
    noteFB._addedBlocks.needEndBlock[noteFB._blockIndex] =
        noteFB._addedBlocks.retVal;
    return noteFB;
  }

  NoteFilterBuilder lessThan(dynamic pValue) {
    param.expression = '<';
    noteFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, noteFB.parameters, param, SqlSyntax.LessThan,
            noteFB._addedBlocks)
        : setCriteria(pValue, noteFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, noteFB._addedBlocks);
    _waitingNot = '';
    noteFB._addedBlocks.needEndBlock[noteFB._blockIndex] =
        noteFB._addedBlocks.retVal;
    return noteFB;
  }

  NoteFilterBuilder greaterThanOrEquals(dynamic pValue) {
    param.expression = '>=';
    noteFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, noteFB.parameters, param,
            SqlSyntax.GreaterThanOrEquals, noteFB._addedBlocks)
        : setCriteria(pValue, noteFB.parameters, param, SqlSyntax.LessThan,
            noteFB._addedBlocks);
    _waitingNot = '';
    noteFB._addedBlocks.needEndBlock[noteFB._blockIndex] =
        noteFB._addedBlocks.retVal;
    return noteFB;
  }

  NoteFilterBuilder lessThanOrEquals(dynamic pValue) {
    param.expression = '<=';
    noteFB._addedBlocks = _waitingNot == ''
        ? setCriteria(pValue, noteFB.parameters, param,
            SqlSyntax.LessThanOrEquals, noteFB._addedBlocks)
        : setCriteria(pValue, noteFB.parameters, param, SqlSyntax.GreaterThan,
            noteFB._addedBlocks);
    _waitingNot = '';
    noteFB._addedBlocks.needEndBlock[noteFB._blockIndex] =
        noteFB._addedBlocks.retVal;
    return noteFB;
  }

  NoteFilterBuilder inValues(dynamic pValue) {
    noteFB._addedBlocks = setCriteria(
        pValue,
        noteFB.parameters,
        param,
        SqlSyntax.IN.replaceAll(SqlSyntax.notKeyword, _waitingNot),
        noteFB._addedBlocks);
    _waitingNot = '';
    noteFB._addedBlocks.needEndBlock[noteFB._blockIndex] =
        noteFB._addedBlocks.retVal;
    return noteFB;
  }
}
// endregion NoteField

// region NoteFilterBuilder
class NoteFilterBuilder extends SearchCriteria {
  NoteFilterBuilder(Note obj) {
    whereString = '';
    qparams = QueryParams();
    parameters = <DbParameter>[];
    orderByList = <String>[];
    groupByList = <String>[];
    _addedBlocks = AddedBlocks(<bool>[], <bool>[]);
    _addedBlocks.needEndBlock.add(false);
    _addedBlocks.waitingStartBlock.add(false);
    _pagesize = 0;
    _page = 0;
    _obj = obj;
  }
  AddedBlocks _addedBlocks;
  int _blockIndex = 0;
  List<DbParameter> parameters;
  List<String> orderByList;
  Note _obj;
  QueryParams qparams;
  int _pagesize;
  int _page;

  /// put the sql keyword 'AND'
  NoteFilterBuilder get and {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' AND ';
    }
    return this;
  }

  /// put the sql keyword 'OR'
  NoteFilterBuilder get or {
    if (parameters.isNotEmpty) {
      parameters[parameters.length - 1].wOperator = ' OR ';
    }
    return this;
  }

  /// open parentheses
  NoteFilterBuilder get startBlock {
    _addedBlocks.waitingStartBlock.add(true);
    _addedBlocks.needEndBlock.add(false);
    _blockIndex++;
    if (_blockIndex > 1) {
      _addedBlocks.needEndBlock[_blockIndex - 1] = true;
    }
    return this;
  }

  /// String whereCriteria, write raw query without 'where' keyword. Like this: 'field1 like 'test%' and field2 = 3'
  NoteFilterBuilder where(String whereCriteria, {dynamic parameterValue}) {
    if (whereCriteria != null && whereCriteria != '') {
      final DbParameter param = DbParameter(
          columnName: parameterValue == null ? null : '',
          hasParameter: parameterValue != null);
      _addedBlocks = setCriteria(parameterValue ?? 0, parameters, param,
          '($whereCriteria)', _addedBlocks);
      _addedBlocks.needEndBlock[_blockIndex] = _addedBlocks.retVal;
    }
    return this;
  }

  /// page = page number,
  ///
  /// pagesize = row(s) per page
  NoteFilterBuilder page(int page, int pagesize) {
    if (page > 0) {
      _page = page;
    }
    if (pagesize > 0) {
      _pagesize = pagesize;
    }
    return this;
  }

  /// int count = LIMIT
  NoteFilterBuilder top(int count) {
    if (count > 0) {
      _pagesize = count;
    }
    return this;
  }

  /// close parentheses
  NoteFilterBuilder get endBlock {
    if (_addedBlocks.needEndBlock[_blockIndex]) {
      parameters[parameters.length - 1].whereString += ' ) ';
    }
    _addedBlocks.needEndBlock.removeAt(_blockIndex);
    _addedBlocks.waitingStartBlock.removeAt(_blockIndex);
    _blockIndex--;
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='name, date'
  ///
  /// Example 2: argFields = ['name', 'date']
  NoteFilterBuilder orderBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add(argFields);
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            orderByList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  NoteFilterBuilder orderByDesc(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        orderByList.add('$argFields desc ');
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            orderByList.add(' $s desc ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='field1, field2'
  ///
  /// Example 2: argFields = ['field1', 'field2']
  NoteFilterBuilder groupBy(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        groupByList.add(' $argFields ');
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            groupByList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  /// argFields might be String or List<String>.
  ///
  /// Example 1: argFields='name, date'
  ///
  /// Example 2: argFields = ['name', 'date']
  NoteFilterBuilder having(dynamic argFields) {
    if (argFields != null) {
      if (argFields is String) {
        havingList.add(argFields);
      } else {
        for (String s in argFields as List<String>) {
          if (s != null && s.isNotEmpty) {
            havingList.add(' $s ');
          }
        }
      }
    }
    return this;
  }

  NoteField setField(NoteField field, String colName, DbType dbtype) {
    return NoteField(this)
      ..param = DbParameter(
          dbType: dbtype,
          columnName: colName,
          wStartBlock: _addedBlocks.waitingStartBlock[_blockIndex]);
  }

  NoteField _id;
  NoteField get id {
    return _id = setField(_id, 'id', DbType.integer);
  }

  NoteField _title;
  NoteField get title {
    return _title = setField(_title, 'title', DbType.text);
  }

  NoteField _context;
  NoteField get context {
    return _context = setField(_context, 'context', DbType.text);
  }

  NoteField _is_synced;
  NoteField get is_synced {
    return _is_synced = setField(_is_synced, 'is_synced', DbType.bool);
  }

  NoteField _created_date;
  NoteField get created_date {
    return _created_date =
        setField(_created_date, 'created_date', DbType.datetime);
  }

  bool _getIsDeleted;

  void _buildParameters() {
    if (_page > 0 && _pagesize > 0) {
      qparams
        ..limit = _pagesize
        ..offset = (_page - 1) * _pagesize;
    } else {
      qparams
        ..limit = _pagesize
        ..offset = _page;
    }
    for (DbParameter param in parameters) {
      if (param.columnName != null) {
        if (param.value is List && !param.hasParameter) {
          param.value = param.dbType == DbType.text
              ? '\'${param.value.join('\',\'')}\''
              : param.value.join(',');
          whereString += param.whereString
              .replaceAll('{field}', param.columnName)
              .replaceAll('?', param.value.toString());
          param.value = null;
        } else {
          if (param.value is Map<String, dynamic> &&
              param.value['sql'] != null) {
            param
              ..whereString = param.whereString
                  .replaceAll('?', param.value['sql'].toString())
              ..dbType = DbType.integer
              ..value = param.value['args'];
          }
          whereString +=
              param.whereString.replaceAll('{field}', param.columnName);
        }
        if (!param.whereString.contains('?')) {
        } else {
          switch (param.dbType) {
            case DbType.bool:
              param.value = param.value == null
                  ? null
                  : param.value == true
                      ? 1
                      : 0;
              param.value2 = param.value2 == null
                  ? null
                  : param.value2 == true
                      ? 1
                      : 0;
              break;
            case DbType.date:
            case DbType.datetime:
            case DbType.datetimeUtc:
              param.value = param.value == null
                  ? null
                  : (param.value as DateTime).millisecondsSinceEpoch;
              param.value2 = param.value2 == null
                  ? null
                  : (param.value2 as DateTime).millisecondsSinceEpoch;
              break;
            default:
          }
          if (param.value != null) {
            if (param.value is List) {
              for (var p in param.value) {
                whereArguments.add(p);
              }
            } else {
              whereArguments.add(param.value);
            }
          }
          if (param.value2 != null) {
            whereArguments.add(param.value2);
          }
        }
      } else {
        whereString += param.whereString;
      }
    }
    if (Note._softDeleteActivated) {
      if (whereString != '') {
        whereString =
            '${!_getIsDeleted ? 'ifnull(isDeleted,0)=0 AND' : ''} ($whereString)';
      } else if (!_getIsDeleted) {
        whereString = 'ifnull(isDeleted,0)=0';
      }
    }

    if (whereString != '') {
      qparams.whereString = whereString;
    }
    qparams
      ..whereArguments = whereArguments
      ..groupBy = groupByList.join(',')
      ..orderBy = orderByList.join(',')
      ..having = havingList.join(',');
  }

  /// Deletes List<Note> bulk by query
  ///
  /// <returns>BoolResult res.success=Deleted, not res.success=Can not deleted
  Future<BoolResult> delete([bool hardDelete = false]) async {
    _buildParameters();
    var r = BoolResult();

    if (Note._softDeleteActivated && !hardDelete) {
      r = await _obj._mnNote.updateBatch(qparams, {'isDeleted': 1});
    } else {
      r = await _obj._mnNote.delete(qparams);
    }
    return r;
  }

  /// using:
  ///
  /// update({'fieldName': Value})
  ///
  /// fieldName must be String. Value is dynamic, it can be any of the (int, bool, String.. )
  Future<BoolResult> update(Map<String, dynamic> values) {
    _buildParameters();
    if (qparams.limit > 0 || qparams.offset > 0) {
      qparams.whereString =
          'id IN (SELECT id from notes ${qparams.whereString.isNotEmpty ? 'WHERE ${qparams.whereString}' : ''}${qparams.limit > 0 ? ' LIMIT ${qparams.limit}' : ''}${qparams.offset > 0 ? ' OFFSET ${qparams.offset}' : ''})';
    }
    return _obj._mnNote.updateBatch(qparams, values);
  }

  /// This method always returns Note Obj if exist, otherwise returns null
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: toSingle(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: toSingle(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>List<Note>
  Future<Note> toSingle(
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    _pagesize = 1;
    _buildParameters();
    final objFuture = _obj._mnNote.toList(qparams);
    final data = await objFuture;
    Note obj;
    if (data.isNotEmpty) {
      obj = Note.fromMap(data[0] as Map<String, dynamic>);
    } else {
      obj = null;
    }
    return obj;
  }

  /// This method returns int. [Note]
  ///
  /// <returns>int
  Future<int> toCount([VoidCallback Function(int c) noteCount]) async {
    _buildParameters();
    qparams.selectColumns = ['COUNT(1) AS CNT'];
    final notesFuture = await _obj._mnNote.toList(qparams);
    final int count = notesFuture[0]['CNT'] as int;
    if (noteCount != null) {
      noteCount(count);
    }
    return count;
  }

  /// This method returns List<Note> [Note]
  ///
  /// bool preload: if true, loads all related child objects (Set preload to true if you want to load all fields related to child or parent)
  ///
  /// ex: toList(preload:true) -> Loads all related objects
  ///
  /// List<String> preloadFields: specify the fields you want to preload (preload parameter's value should also be "true")
  ///
  /// ex: toList(preload:true, preloadFields:['plField1','plField2'... etc])  -> Loads only certain fields what you specified
  ///
  /// bool loadParents: if true, loads all parent objects until the object has no parent

  ///
  /// <returns>List<Note>
  Future<List<Note>> toList(
      {bool preload = false,
      List<String> preloadFields,
      bool loadParents = false,
      List<String> loadedFields}) async {
    final data = await toMapList();
    final List<Note> notesData = await Note.fromMapList(data,
        preload: preload,
        preloadFields: preloadFields,
        loadParents: loadParents,
        loadedFields: loadedFields,
        setDefaultValues: qparams.selectColumns == null);
    return notesData;
  }

  /// This method returns Json String [Note]
  Future<String> toJson() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(o.toMap(forJson: true));
    }
    return json.encode(list);
  }

  /// This method returns Json String. [Note]
  Future<String> toJsonWithChilds() async {
    final list = <dynamic>[];
    final data = await toList();
    for (var o in data) {
      list.add(await o.toMapWithChildren(false, true));
    }
    return json.encode(list);
  }

  /// This method returns List<dynamic>. [Note]
  ///
  /// <returns>List<dynamic>
  Future<List<dynamic>> toMapList() async {
    _buildParameters();
    return await _obj._mnNote.toList(qparams);
  }

  /// This method returns Primary Key List SQL and Parameters retVal = Map<String,dynamic>. [Note]
  ///
  /// retVal['sql'] = SQL statement string, retVal['args'] = whereArguments List<dynamic>;
  ///
  /// <returns>List<String>
  Map<String, dynamic> toListPrimaryKeySQL([bool buildParameters = true]) {
    final Map<String, dynamic> _retVal = <String, dynamic>{};
    if (buildParameters) {
      _buildParameters();
    }
    _retVal['sql'] = 'SELECT `id` FROM notes WHERE ${qparams.whereString}';
    _retVal['args'] = qparams.whereArguments;
    return _retVal;
  }

  /// This method returns Primary Key List<int>.
  /// <returns>List<int>
  Future<List<int>> toListPrimaryKey([bool buildParameters = true]) async {
    if (buildParameters) {
      _buildParameters();
    }
    final List<int> idData = <int>[];
    qparams.selectColumns = ['id'];
    final idFuture = await _obj._mnNote.toList(qparams);

    final int count = idFuture.length;
    for (int i = 0; i < count; i++) {
      idData.add(idFuture[i]['id'] as int);
    }
    return idData;
  }

  /// Returns List<dynamic> for selected columns. Use this method for 'groupBy' with min,max,avg..  [Note]
  ///
  /// Sample usage: (see EXAMPLE 4.2 at https://github.com/hhtokpinar/sqfEntity#group-by)
  Future<List<dynamic>> toListObject() async {
    _buildParameters();

    final objectFuture = _obj._mnNote.toList(qparams);

    final List<dynamic> objectsData = <dynamic>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i]);
    }
    return objectsData;
  }

  /// Returns List<String> for selected first column
  ///
  /// Sample usage: await Note.select(columnsToSelect: ['columnName']).toListString()
  Future<List<String>> toListString(
      [VoidCallback Function(List<String> o) listString]) async {
    _buildParameters();

    final objectFuture = _obj._mnNote.toList(qparams);

    final List<String> objectsData = <String>[];
    final data = await objectFuture;
    final int count = data.length;
    for (int i = 0; i < count; i++) {
      objectsData.add(data[i][qparams.selectColumns[0]].toString());
    }
    if (listString != null) {
      listString(objectsData);
    }
    return objectsData;
  }
}
// endregion NoteFilterBuilder

// region NoteFields
class NoteFields {
  static TableField _fId;
  static TableField get id {
    return _fId = _fId ?? SqlSyntax.setField(_fId, 'id', DbType.integer);
  }

  static TableField _fTitle;
  static TableField get title {
    return _fTitle =
        _fTitle ?? SqlSyntax.setField(_fTitle, 'title', DbType.text);
  }

  static TableField _fContext;
  static TableField get context {
    return _fContext =
        _fContext ?? SqlSyntax.setField(_fContext, 'context', DbType.text);
  }

  static TableField _fIs_synced;
  static TableField get is_synced {
    return _fIs_synced = _fIs_synced ??
        SqlSyntax.setField(_fIs_synced, 'is_synced', DbType.bool);
  }

  static TableField _fCreated_date;
  static TableField get created_date {
    return _fCreated_date = _fCreated_date ??
        SqlSyntax.setField(_fCreated_date, 'created_date', DbType.datetime);
  }
}
// endregion NoteFields

//region NoteManager
class NoteManager extends SqfEntityProvider {
  NoteManager()
      : super(MyDbModel(),
            tableName: _tableName,
            primaryKeyList: _primaryKeyList,
            whereStr: _whereStr);
  static final String _tableName = 'notes';
  static final List<String> _primaryKeyList = ['id'];
  static final String _whereStr = 'id=?';
}

//endregion NoteManager
/// Region SEQUENCE IdentitySequence
class IdentitySequence {
  /// Assigns a new value when it is triggered and returns the new value
  /// returns Future<int>
  Future<int> nextVal([VoidCallback Function(int o) nextval]) async {
    final val = await MyDbModelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, true);
    if (nextval != null) {
      nextval(val);
    }
    return val;
  }

  /// Get the current value
  /// returns Future<int>
  Future<int> currentVal([VoidCallback Function(int o) currentval]) async {
    final val = await MyDbModelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, false);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }

  /// Reset sequence to start value
  /// returns start value
  Future<int> reset([VoidCallback Function(int o) currentval]) async {
    final val = await MyDbModelSequenceManager()
        .sequence(SequenceIdentitySequence.getInstance, false, reset: true);
    if (currentval != null) {
      currentval(val);
    }
    return val;
  }
}

/// End Region SEQUENCE IdentitySequence

class MyDbModelSequenceManager extends SqfEntityProvider {
  MyDbModelSequenceManager() : super(MyDbModel());
}
// END OF ENTITIES
